config/routes.rb
SpottyMouth::Application.routes.draw do
  resources :users, :except => [:edit, :update] do
    match '/changepassword' => 'passwords#edit', :via => :get
    match '/passwordreset' => 'passwords#update', :via => :put
    resources :insults, :only => [:index, :create]
    member do
      get :following, :followers, :voters_for, :voters_against
    end
  end
  resources :insults, :only => [] do
    resources :comments, :only => [:index, :new, :create]
  end
  resources :daily_questions, :except => [:edit] do
    resources :daily_answers, :only => :create
  end
  
  resource :user, :only => [:edit, :update]
  
  resources :passwords, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :insults, :only => [:destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :comments, :only => [:destroy]
  resources :daily_answers, :only => :destroy
  resources :answer_marks, :only => [:create, :destroy]

  match ':controller/:id/voters_for' => 'insults#voters_for', :as => :voters_for_insult
  match ':controller/:id/voters_against' => 'insults#voters_against', :as => :voters_against_insult
  match '/forgot_password', :to => 'passwords#new'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/terms_and_conditions', :to => 'pages#terms_and_conditions'
  match '/findvictim', :to => 'pages#find_victim'
  match '/votedownuser/:id' => 'votes#vote_down_user', :as => :vote_down_user
  match '/voteupuser/:id' => 'votes#vote_up_user', :as => :vote_up_user
  match '/votedowninsult/:id' => 'votes#vote_down_insult', :as => :vote_down_insult
  match '/voteupinsult/:id' => 'votes#vote_up_insult', :as => :vote_up_insult
  match '/walloffame', :to => 'walls#wall_of_fame'
  match '/wallofshame', :to => 'walls#wall_of_shame'
  match '/beef_with/:id' => 'users#beef_with', :as => :beef_with
  match '/archive' => 'daily_questions#archive', :as => :daily_questions_archive
  root :to => 'pages#home'
end

app/models/answer_mark.rb
class AnswerMark < ActiveRecord::Base
  attr_accessible :answer_id
  
  belongs_to :user
  belongs_to :question, :class_name => "DailyQuestion"
  has_one :answer, :class_name => "DailyAnswer", :dependent => :nullify
  
  validates_uniqueness_of :user_id, :scope => :question_id
  validates_uniqueness_of :answer_id
  
  validates :user_id, :presence => true
  validates :answer_id, :presence => true
  validates :question_id, :presence => true
  
  before_validation :assign_attributes
  
  private
  
    def assign_attributes
      unless self.answer_id.blank?
	da = DailyAnswer.find(self.answer_id)
	self.answer = da
	self.user = da.user
	self.question = da.daily_question
      end
	# self.user = DailyAnswer.find(self.answer_id).user unless self.answer_id.blank?
    end
end

app/controllers/answer_marks_controller.rb
class AnswerMarksController < ApplicationController
  before_filter :authenticate
  before_filter :allowed_to_create, :only => [:create]
  before_filter :allowed_to_destroy, :only => [:destroy]
  
  respond_to :html, :js
  
  def create
    @answer_mark = AnswerMark.new(:answer_id => params[:id])
    if @answer_mark.save
      respond_with(@answer_mark) do |format|
	format.html { redirect_to daily_question_path(@answer_mark.question) }
      end
    else
      daily_answer = DailyAnswer.find(params[:id])
      flash[:error] = "Setting could not be saved."
      redirect_to daily_question_path(daily_answer.daily_question)
    end
  end

  def destroy
    @answer_mark.destroy
    set_user_variables
    respond_with(@answer_mark) do |format|
      format.html { redirect_to daily_question_path(@answer_mark.question) }
    end
  end
  
  def set_user_variables
    @user_answers_ids = current_user.daily_answers.
	where(:daily_question_id => @answer_mark.question_id)
  end

  
  private
    
    def allowed_to_create
      daily_answer = DailyAnswer.find(params[:id])
      redirect_to(root_path) unless current_user?(daily_answer.user)
    end
    
    def allowed_to_destroy
      @answer_mark = AnswerMark.find(params[:id])
      redirect_to(root_path) unless current_user?(@answer_mark.user)
    end
end

app/helpers/answer_marks_helper.rb
module AnswerMarksHelper
end

app/views/answer_marks/_mark_answer.html.erb
<span class="marking_link"><%= (link_to "Mark as Answer", answer_marks_path(:id => answer.id), 
				  :method => :post, :remote => true) %> |</span>

app/views/answer_marks/_unmark_answer.html.erb
<%= (link_to "Unmark", answer_mark_path(answer_mark.id), 
				  :method => :delete, :remote => true) %> | 

app/views/answer_marks/create.js.erb
$("answer_<%= @answer_mark.answer_id %>").addClassName("marked_answer");
$("answer_<%= @answer_mark.answer_id %>_link").update('<%= render :partial => "answer_marks/unmark_answer", 
	      :locals => {:answer_mark => @answer_mark } %>');
myArray = $(document).getElementsByClassName('marking_link');
for(var i=myArray.length-1; i >= 0; i--){
  myArray[i].remove();
}

app/views/answer_marks/destroy.js.erb
$("answer_<%= @answer_mark.answer_id %>").removeClassName("marked_answer");
<% if @user_answers_ids %>
  <% @user_answers_ids.each do |answer| %>
    $("answer_<%= answer.id %>_link").update('<%= render :partial => "answer_marks/mark_answer", 
	      :locals => {:answer => answer } %>');
  <% end %>
<% end %>