config/routes.rb
SpottyMouth::Application.routes.draw do
  resources :users, :except => [:edit, :update] do
    match '/changepassword' => 'passwords#edit', :via => :get
    match '/passwordreset' => 'passwords#update', :via => :put
    resources :insults, :only => [:index, :create]
    member do
      get :following, :followers, :voters_for, :voters_against
    end
  end
  resources :insults, :only => [] do
    resources :comments, :only => [:index, :new, :create]
  end
  resources :daily_questions, :except => [:edit] do
    resources :daily_answers, :only => :create
  end
  
  resource :user, :only => [:edit, :update]
  
  resources :passwords, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :insults, :only => [:destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :comments, :only => [:destroy]
  resources :daily_answers, :only => :destroy
  resources :answer_marks, :only => [:create, :destroy]

  match ':controller/:id/voters_for' => 'insults#voters_for', :as => :voters_for_insult
  match ':controller/:id/voters_against' => 'insults#voters_against', :as => :voters_against_insult
  match '/forgot_password', :to => 'passwords#new'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/terms_and_conditions', :to => 'pages#terms_and_conditions'
  match '/findvictim', :to => 'pages#find_victim'
  match '/votedownuser/:id' => 'votes#vote_down_user', :as => :vote_down_user
  match '/voteupuser/:id' => 'votes#vote_up_user', :as => :vote_up_user
  match '/votedowninsult/:id' => 'votes#vote_down_insult', :as => :vote_down_insult
  match '/voteupinsult/:id' => 'votes#vote_up_insult', :as => :vote_up_insult
  match '/walloffame', :to => 'walls#wall_of_fame'
  match '/wallofshame', :to => 'walls#wall_of_shame'
  match '/beef_with/:id' => 'users#beef_with', :as => :beef_with
  match '/archive' => 'daily_questions#archive', :as => :daily_questions_archive
  root :to => 'pages#home'
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  # Potential TO-DO: validate image size before caching
  attr_accessor :password, :updating_password
  attr_accessible :username, :email, :password, :password_confirmation, :image, :blurb
  attr_readonly :username, :email
  mount_uploader :image, ImageUploader
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  has_many :insults, :foreign_key => :insulted_id,
		     :dependent => :destroy  
  has_many :reverse_insults, :foreign_key => :insulter_id,
			     :class_name => "Insult",
			     :dependent => :destroy
  has_many :relationships, :foreign_key => :follower_id,
			   :dependent => :destroy
  has_many :reverse_relationships, :foreign_key => :followed_id,
				   :class_name => "Relationship",
				   :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_many :comments, :foreign_key => :commenter_id,
		      :dependent => :destroy
  has_many :daily_answers, :dependent => :destroy
  has_many :answer_marks, :dependent => :destroy
  has_many :marked_answers, :through => :answer_marks, :source => :answer
  
  validates :username, :presence => true,
		       :uniqueness => { :case_sensitive => false },
		       :length => { :minimum => 4,
                                :maximum => 30 }
  
  validates :email, :presence => true,
		    :format => { :with => email_regex },
		    :uniqueness => { :case_sensitive => false }
  
  validates :password, :presence => true,
		       :confirmation => true,
		       :length => { :within => 6..40 },# Automatically create the virtual attribute 'password confirmation'
		       :if => :should_validate_password?
  
  validates_length_of :blurb, :maximum => 600
  
  before_validation :strip_whitespace
  before_save :encrypt_password, :if => :should_validate_password?
  
  acts_as_voter
  acts_as_voteable
  
  def should_validate_password?
    updating_password || new_record?
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
    return nil
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed.id)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed.id).destroy
  end
  
  def already_marked_answer?(question)
    marked_answers.find_by_daily_question_id(question.id)
  end
  
  # Kept getting undefined method when trying to inherit this method, so 
  # wrote this custom override
  def new_record?
    self.id.nil? ? true : false
  end
  
  def add_insult!(insulter, content)
    self.insults.create!(:insulter_id => insulter.id, :content => content)
  end
  
  def insult_delete_power?(insult)
    (self == insult.insulted) || (self == insult.insulter) || self.admin?
  end
  
  def comment_delete_power?(comment)
    (self == comment.commenter) || (self == comment.insult.insulted) || self.admin?
  end
  
  def feed
    Insult.from_users_followed_by(self)
  end
  
  private
  
    def strip_whitespace
      self.username = self.username.strip unless self.username.blank?
      self.blurb = self.blurb.strip unless self.blurb.blank?
    end
    
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
    def image_size_validation
      errors[:image] << "should be less than 2 MB" if image.size > 2.megabytes
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :authenticate2, :only => [:new, :create]
  before_filter :admin_user,	:only => :destroy
  before_filter :correct_user, 	:only => :update

  def show
    @user = User.find(params[:id])
    @insults = @user.insults.paginate(:page => params[:page])
    @insult = Insult.new
    @title = helpers.sanitize(@user.username, :tags => "")
    @daily_question = DailyQuestion.first
    if @daily_question && @user.already_marked_answer?(@daily_question)
      @user_marked_answer = AnswerMark.find_by_question_id_and_user_id(
			      @daily_question.id, @user.id)
    end
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
      if @user.valid? && verify_recaptcha()
	@user.save
	sign_in @user
	flash[:success] = "Successful Registration!"
	redirect_to @user
      else
	if !verify_recaptcha()
	  flash[:error] = "The verification was not correct.  Please try again."
	end
	# Clear passwords
	@user.password = ""
	@user.password_confirmation = ""
	@title = "Sign up"
	render 'new'
      end
  end
  
  def edit
    @user = current_user
    @title = current_user.username + " Edit"
  end
  
  def update
    @user = current_user
    @user.image = params[:user][:image]
    begin
      @user.update_attributes!(params[:user])
      flash[:success] = "Profile updated successfully!"
      redirect_to user_path(@user)
    rescue
      flash[:error] = "Changes could not be saved."
      @user.errors.add(:upload, @user.image_integrity_error) if @user.image_integrity_error
      render 'edit'
    end
  end
  
  def destroy
    # Uses current_user.id, which by default must be an admin ID, and checks
    # if user to delete is the admin itself, in which case an error is thrown
    @user = User.find(params[:id])
    if current_user.id == @user.id
      flash[:error] = "Deletion of self as admin is not allowed."
    else
    @user.destroy
    flash[:success] = "User destroyed."
    end
    redirect_to root_path
  end
  
  def following 
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def voters_for
    @user = User.find(params[:id])
    @voters = @user.votes.where(:vote => true).map(&:voter).uniq.paginate(:page => params[:page])
    render 'shared/show_voters'
  end
  
  def voters_against
    @user = User.find(params[:id])
    @voters = @user.votes.where(:vote => false).map(&:voter).uniq.paginate(:page => params[:page])
    render 'shared/show_voters'
  end
  
  def beef_with
    @user = User.find(params[:id])
    t = Insult.where("(insulter_id = :current_user AND insulted_id = :user) 
                            OR (insulter_id = :user AND insulted_id = :current_user)",
                     { :current_user => current_user, :user => @user })
    @insults = t.select("*").paginate(:page => params[:page])
  end
  
  # To include sanitize method
  def helpers
    Helper.instance
  end

  class Helper
    include Singleton
    include ActionView::Helpers::TextHelper
  end

  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  

end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |f| %>
<div><%= f.hidden_field :followed_id %></div>
<div class="actions"><%= f.submit "Target" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'users/unfollow' %>
    <% else %>
      <%= render 'users/follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
		:html => { :method => :delete }, :remote => true do |f| %>
<div class="actions"><%= f.submit "Untarget" %></div>
<% end %>

app/views/users/_useredit.html.erb
<%= render 'shared/error_messages', :object => f.object %>
  <%= f.hidden_field :id %>
  <%= f.file_field :image %> <br />
  <%= f.submit "Update Image" %>

app/views/users/beef_with.html.erb
<p>Beef between you and <em><%= link_to @user.username, user_path(@user) %></em>:</p>
<% unless @insults.empty? %>
  <%= render :partial => 'insults/insult', :collection => @insults %>
  <%= will_paginate @insults %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit - <%= @user.username %></h1>
<div class="sidebar">
  <%= link_to "Change Password", user_changepassword_path(@user) %>
</div>
<%= form_for(@user, :as => :user, :url => { :controller => 'users', :action => 'update' }, :html => { :multipart => true, :method => 'put' }) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= hidden_field_tag(:id, @user.id) %>
  <h3>Profile Picture</h3>
  <span>
    <%= image_tag @user.image_url.to_s, :class => 'avatar' %>
    <%= f.file_field :image %> <br />
  </span>
  <div>
    <%= f.text_area :blurb %>
  </div>
  <div class="actions">
    <%= f.submit "Save Changes" %> or <%= link_to 'Cancel', user_path(@user) %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <%= recaptcha_tags %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile" summary="Profile Information">
    <div class="sidebar">
      <% if signed_in? %>
	<% if current_user?(@user) %>
	  <%= link_to "Edit Profile", edit_user_path %> <br />
	<% end %>
	<% if current_user.admin? %>
	  <%= link_to "Delete", @user, :method => :delete, :confirm => "You sure?" %>
	  <br />
	<% end %>
      <% end %>
    </div>
    <div class="main">
	<h1>
	  <%= image_tag @user.image_url.to_s, :class => 'avatar' %>
	  <%= clean_name(@user.username) %>
	</h1>
	<%= wrap(@user.blurb) %>
      <div class="user_dashboard">
	<% unless current_user?(@user) %>
	  <div>View your <%= link_to "beef", beef_with_path(@user) %> with this hater.</div>
	<% end %>
	<%= render :partial => 'shared/user_number_links', :locals => { :user => @user } %>
	<div class="userfollowdiv">
	  <%= render 'users/follow_form' if signed_in? %>
	</div>
	<div class="userratingdiv">
	  <%= render 'shared/user_vote' %>
	</div>
	<div class="clearer"></div>
      </div>
	<%= render 'shared/stats' %>
      <p>
	<% if @daily_question %>
	  This hater's answer to the <%= link_to "Daily Question", 
	    daily_question_path(@daily_question) %> <br />
	  <strong>
	    <% if @user_marked_answer %>
	      <%= @user_marked_answer.answer.content %>
	    <% else %>
	      No Answer Yet
	    <% end %>
	  </strong>
	<% end %>
      </p >
    </div>
</div>
<div id="insult_div">
  <% if signed_in? %>
    Spit some fire on this wall:
    <%= render 'shared/insult_post' %>
  <% else %>
    <%= render 'shared/login_prompt', :object_name => "burn" %>
  <% end %>
  <% unless @user.insults.empty? %>
    <%= render @insults %>
    <%= will_paginate @insults %>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% unless @users.empty? %>
<ul class="users">
  <%= render :partial => 'shared/user_tag', :collection => @users, :as => :user %>
</ul>
<%= will_paginate @users %>
<% end %>