config/routes.rb
SpottyMouth::Application.routes.draw do
  resources :users, :except => [:edit, :update] do
    match '/changepassword' => 'passwords#edit', :via => :get
    match '/passwordreset' => 'passwords#update', :via => :put
    resources :insults, :only => [:index, :create]
    member do
      get :following, :followers, :voters_for, :voters_against
    end
  end
  resources :insults, :only => [] do
    resources :comments, :only => [:index, :new, :create]
  end
  resources :daily_questions, :except => [:edit] do
    resources :daily_answers, :only => :create
  end
  
  resource :user, :only => [:edit, :update]
  
  resources :passwords, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :insults, :only => [:destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :comments, :only => [:destroy]
  resources :daily_answers, :only => :destroy
  resources :answer_marks, :only => [:create, :destroy]

  match ':controller/:id/voters_for' => 'insults#voters_for', :as => :voters_for_insult
  match ':controller/:id/voters_against' => 'insults#voters_against', :as => :voters_against_insult
  match '/forgot_password', :to => 'passwords#new'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/terms_and_conditions', :to => 'pages#terms_and_conditions'
  match '/findvictim', :to => 'pages#find_victim'
  match '/votedownuser/:id' => 'votes#vote_down_user', :as => :vote_down_user
  match '/voteupuser/:id' => 'votes#vote_up_user', :as => :vote_up_user
  match '/votedowninsult/:id' => 'votes#vote_down_insult', :as => :vote_down_insult
  match '/voteupinsult/:id' => 'votes#vote_up_insult', :as => :vote_up_insult
  match '/walloffame', :to => 'walls#wall_of_fame'
  match '/wallofshame', :to => 'walls#wall_of_shame'
  match '/beef_with/:id' => 'users#beef_with', :as => :beef_with
  match '/archive' => 'daily_questions#archive', :as => :daily_questions_archive
  root :to => 'pages#home'
end

app/models/daily_question.rb
class DailyQuestion < ActiveRecord::Base
  attr_accessible :content
  cattr_reader :per_page
  
  @@per_page = 31
  
  has_many :daily_answers, :dependent => :destroy
  has_many :answer_marks, :foreign_key => :question_id,
			  :dependent => :destroy
  has_many :marked_answers, :through => :answer_marks, :source => :answer
  
  validates :content, :presence => true,
		      :length => { :maximum => 255 }
  
  before_validation :strip_whitespace
  
  default_scope :order => 'daily_questions.created_at DESC'
  
  private
  
    def strip_whitespace
      self.content = self.content.strip unless self.content.blank?
    end
end

app/controllers/daily_questions_controller.rb
class DailyQuestionsController < ApplicationController
  before_filter :admin_user, :except => [:index, :show, :archive]
  
  def index
    @daily_question = DailyQuestion.first
    @daily_answers = @daily_question.daily_answers.paginate(
			:page => params[:page]) unless @daily_question.nil?
    set_user_variables if signed_in?
    @daily_answer = DailyAnswer.new
  end

  def show
    @daily_question = DailyQuestion.find(params[:id])
    @daily_answers = @daily_question.daily_answers.paginate(
			:page => params[:page]) unless @daily_question.nil?
    set_user_variables if signed_in?
    @daily_answer = DailyAnswer.new
  end
  
  def archive
    date = params[:timeframe].blank? ? nil : Time.parse(params[:timeframe])
    unless date.nil?
      @daily_questions = DailyQuestion.all(:conditions => 
                              { :created_at => date.beginning_of_month..date.end_of_month }).
			      paginate(:page => params[:page])
    else
      @daily_questions = DailyQuestion.paginate(:page => params[:page])
    end
  end

  def new
    @daily_question = DailyQuestion.new
  end

  def create
    @daily_question = DailyQuestion.new(params[:daily_question])
    if @daily_question.save
      flash[:success] = "Question added."
      redirect_to @daily_question
    else
      flash[:error] = "The question could not be saved."
      render 'daily_questions/new'
    end
  end

  def destroy
    @daily_question = DailyQuestion.find(params[:id])
    @daily_question.destroy
    flash[:success] =  "Question destroyed."
    redirect_to daily_questions_path
  end
  
  def set_user_variables
    # @user_answers = @daily_answers.find_all { 
    #  |u| u.user_id == current_user.id }.map { |u| u.id }
    @already_answered = true if current_user.already_marked_answer?(@daily_question)
  end
end

app/helpers/daily_questions_helper.rb
module DailyQuestionsHelper
  def question_months
    DailyQuestion.all(:select => "created_at").group_by { |m| m.created_at.beginning_of_month }
  end
end

app/views/daily_questions/_archive_list.html.erb
<tr>
  <td><%= link_to truncate(question.content, :length => 50), daily_question_path(question) %></td>
  <td>Posted <%= time_ago_in_words(question.created_at) %> ago.</td>
</tr>

app/views/daily_questions/_show_question.html.erb
<% if signed_in? %>
  <% if current_user.admin? %>
    <%= link_to "Add new question", new_daily_question_path %> <br />
  <% end %>
<% end %>
<%= link_to "View the Archive", daily_questions_archive_path %>
<% unless @daily_question.nil? %>
  <div class="daily_question">
    <%= @daily_question.content %>
  </div>
  <% if !signed_in? %>
    <%= render 'shared/login_prompt', :object_name => "comment" %>
  <% else %>
    <%= render 'daily_answers/answer_post' %>
  <% end %>
  <% unless @daily_answers.empty? %>
    <%= render :partial => 'daily_answers/answer', :collection => @daily_answers, :as => :answer %>
    <%= will_paginate @daily_answers %>
  <% end %>
<% end %>

app/views/daily_questions/_sidebar.html.erb
<div id="archiveList">
    <span>Archive:</span>
    <ul>
      <li><%= link_to "All", daily_questions_archive_path %></li>
      <% unless question_months.empty? %>
	<% question_months.sort.reverse.each do |month, questions| %>
	  <li><%= link_to "#{h month.strftime("%B %y")}",
			    daily_questions_archive_path(:timeframe => month) %></li>
	<% end %>
      <% end %>
    </ul>
</div>

app/views/daily_questions/archive.html.erb
<div id="archiveWrap">
 <%= render 'sidebar' %>
<% unless @daily_questions.empty? %>
  <table>
    <tr>
      <td><h3>Question</h3></td>
      <td><h3>Posted</h3></td>
    </tr>
    <%= render(:partial => 'archive_list', :collection => @daily_questions, :as => :question) %>
  </table>
<%= will_paginate %>
<% end %>
</div>

app/views/daily_questions/index.html.erb
<h1>Question of the Day</h1>
<%= render 'daily_questions/show_question' %>

app/views/daily_questions/new.html.erb
<%= form_for @daily_question do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/daily_questions/show.html.erb
<%= render 'daily_questions/show_question' %>