config/routes.rb
SpottyMouth::Application.routes.draw do
  resources :users, :except => [:edit, :update] do
    match '/changepassword' => 'passwords#edit', :via => :get
    match '/passwordreset' => 'passwords#update', :via => :put
    resources :insults, :only => [:index, :create]
    member do
      get :following, :followers, :voters_for, :voters_against
    end
  end
  resources :insults, :only => [] do
    resources :comments, :only => [:index, :new, :create]
  end
  resources :daily_questions, :except => [:edit] do
    resources :daily_answers, :only => :create
  end
  
  resource :user, :only => [:edit, :update]
  
  resources :passwords, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :insults, :only => [:destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :comments, :only => [:destroy]
  resources :daily_answers, :only => :destroy
  resources :answer_marks, :only => [:create, :destroy]

  match ':controller/:id/voters_for' => 'insults#voters_for', :as => :voters_for_insult
  match ':controller/:id/voters_against' => 'insults#voters_against', :as => :voters_against_insult
  match '/forgot_password', :to => 'passwords#new'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/terms_and_conditions', :to => 'pages#terms_and_conditions'
  match '/findvictim', :to => 'pages#find_victim'
  match '/votedownuser/:id' => 'votes#vote_down_user', :as => :vote_down_user
  match '/voteupuser/:id' => 'votes#vote_up_user', :as => :vote_up_user
  match '/votedowninsult/:id' => 'votes#vote_down_insult', :as => :vote_down_insult
  match '/voteupinsult/:id' => 'votes#vote_up_insult', :as => :vote_up_insult
  match '/walloffame', :to => 'walls#wall_of_fame'
  match '/wallofshame', :to => 'walls#wall_of_shame'
  match '/beef_with/:id' => 'users#beef_with', :as => :beef_with
  match '/archive' => 'daily_questions#archive', :as => :daily_questions_archive
  root :to => 'pages#home'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s %> from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <%= render :partial => 'insults/insult', :collection => @feed_items, :as => :insult %>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_insult_info.html.erb
<div class="insult_info">
  <%= insult.content[0,30] %>... by <br /><%= link_to insult.insulter.username, user_path(insult.insulter) %>
  on <%= link_to insult.insulted.username, user_path(insult.insulted) %>'s wall.
  <br /><strong>Rating: </strong><%= insult.plusminus %>
  <br />
  <span><%= link_to "#{pluralize(insult.votes_for, "vote")} for", voters_for_insult_path(insult) %> |</span>
  <span><%= link_to "#{pluralize(insult.votes_against, "vote")} against", voters_against_insult_path(insult) %></span>
</div>
<hr />

app/views/shared/_insult_post.html.erb
<%= form_for [@user, @insult] do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content, :class => 'objectPoster' %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_insult_vote.html.erb
<% uppath = "" %>
<% downpath = "" %>
<% if signed_in? %>
  <% if current_user.voted_for?(insult) %>
    <% uppath += "select" %>
  <% end %>
  <% if current_user.voted_against?(insult) %>
    <% downpath += "select" %>
  <% end %>
<% end %>

<% if signed_in? %>
<%= link_to image_tag("uparrow#{uppath}.png"), vote_up_insult_path(insult.id), 
	  :method => :post, :title => "Ohh Burn", :id => "uparrow#{insult.id}", :class => "arrow", :remote => true %>
<% end %>

<span>Insult Rating: <span id="insult_rating<%= insult.id %>"><%= insult.plusminus.to_s %></span></span>

<% if signed_in? %>
<%= link_to image_tag("downarrow#{downpath}.png"), vote_down_insult_path(insult.id), 
	  :method => :post, :title => "Needs work", :id => "downarrow#{insult.id}", :class =>"arrow", :remote => true %>
<% end %>

app/views/shared/_login_prompt.html.erb
<p class="login_prompt">You must <%= link_to "login", signin_path %> or <%= link_to "register",
	signup_path %> to leave a <%= defined?(object_name) ? object_name : "object" %>.</p>

app/views/shared/_search_form.html.erb
<%= form_tag findvictim_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <div class="right">
    <a href="<%= following_user_path(@user) %>">
    	<span><%= pluralize(@user.following.count, "user") %> in this user's shit list</span>
    </a>
  </div>
  <div>
    <a href="<%= followers_user_path(@user) %>">
      <span id="followers"><%= pluralize(@user.followers.count, "user") %> preying on this hater</span>
    </a>
  </div>
  <div class="clearer"></div>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.image_url.to_s, :class => 'avatar' %>
  </a>
    <span class="user_name">
      <h3><%= link_to clean_name(user.username), user_path(user) %></h3>
    </span>
    <div class="userlinks">
      <%= render :partial => 'shared/user_number_links', :locals => { :user => user } %>
    </div>
</div>
<hr />

app/views/shared/_user_number_links.html.erb
<span class="insults">
  <%= link_to pluralize(Insult.where(:insulter_id => user).count, "insult"), user_insults_path(user) %> |
</span>
<span><%= link_to "#{pluralize(user.votes_for, "vote")} for", voters_for_user_path(user),
			  :id => "votes_for_link" %> |</span>
<span><%= link_to "#{pluralize(user.votes_against, "vote")} against", voters_against_user_path(user),
			  :id => "votes_against_link" %></span>

app/views/shared/_user_tag.html.erb
<li>
  <%= link_to (image_tag user.image_url.to_s, :class => 'avatar'), user_path(user) %>
  <%= link_to clean_name(user.username), user_path(user) %>
  <% if signed_in? %>
    <% if current_user.admin? %>
    |  <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
				    :title => "Delete #{user.username}" %>
    <% end %>
  <% end %>
</li>

app/views/shared/_user_vote.html.erb
<% uppath = "" %>
<% downpath = "" %>
<% if signed_in? %>
  <% if current_user.voted_for?(@user) %>
    <% uppath += "select" %>
  <% end %>
  <% if current_user.voted_against?(@user) %>
    <% downpath += "select" %>
  <% end %>
<% end %>

<% if signed_in? %>
<%= link_to image_tag("uparrowbig#{uppath}.png"), vote_up_user_path(@user), :method => :post,
			:title => "Game is tight", :id => "user_up_arrow", :class => "arrow", :remote => true %>
<% end %>

<h3><strong>Hater Rating: <span id="hater_rating"><%= @user.plusminus.to_s %></span></strong></h3>

<% if signed_in? %>
<%= link_to image_tag("downarrowbig#{downpath}.png"), vote_down_user_path(@user), :method => :post,
				      :title => "Game's weak", :id => "user_down_arrow", :class => "arrow", :remote => true %>
<% end %> 

app/views/shared/show_voters.html.erb
<% if controller.action_name == 'voters_for' %>
<p>
  Users respecting on 
    <% if controller.controller_name == 'users' %>
      <%= link_to clean_name(@user.username), user_path(@user) %>:
    <% elsif controller.controller_name == 'insults' %>
      <p>
	<%= link_to @insult.content, user_path(@insult.insulted) %>:
      </p>
    <% end %>
</p>
<% elsif controller.action_name == 'voters_against' %>
<p>
  Users hating on 
    <% if controller.controller_name == 'users' %>
      <%= link_to clean_name(@user.username), user_path(@user) %>:
    <% elsif controller.controller_name == 'insults' %>
      <p>
	<%= link_to @insult.content, user_path(@insult.insulted) %>:
      </p>
    <% end %>
</p>
<% end %>
<% unless @voters.empty? %>
  <%= render :partial => 'shared/user_info', :collection => @voters,
					     :as => :user %>
  <%= will_paginate @voters %>
<% end %>